
prod:
  hostname: website.com
  user: ulem#ulem.com
  deploy_path: /var/www/ulem.com
  remote_url: https://ulem.com
  local_url: http://ulem.local
  forwardAgent: true
  http_user: ulem

staging:
  hostname: website.com
  user: ulem#ulem.com
  deploy_path: /var/www/staging.ulem.com
  remote_url: https://staging.ulem.com
  local_url: http://ulem.local
  forwardAgent: true
  http_user: ulem
