next:
  hostname: lon1.authoritywit.com
  user: ulem#ulem.org
  branch: env/next
  deploy_path: /var/www/go.ulem.org
  remote_url: https://go.ulem.org
  local_url: http://ulem.local
  forwardAgent: true
  http_user: ulem

prod:
  hostname: site.ulem.org
  user: ulem#ulem.com
  branch: env/prod
  deploy_path: /var/www/ulem.org
  remote_url: https://ulem.org
  local_url: http://ulem.local
  forwardAgent: true
  http_user: ulem

staging:
  hostname: site.ulem.org
  user: ulem#ulem.org
  branch: env/staging
  deploy_path: /var/www/staging.ulem.org
  remote_url: https://staging.ulem.org
  local_url: http://ulem.local
  forwardAgent: true
  http_user: ulem
